---
name: konflux-policy

on:
  workflow_dispatch:
  schedule:
    # At 08:30 UTC on Tuesday
    - cron: '30 8 * * 2'

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:

    - name: Log in to quay.io/enterprise-contract
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.BUNDLE_PUSH_USER_EC }}
        password: ${{ secrets.BUNDLE_PUSH_PASS_EC }}
        registry: quay.io/enterprise-contract

    - name: Log in to quay.io/conforma
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.BUNDLE_PUSH_USER_CONFORMA }}
        password: ${{ secrets.BUNDLE_PUSH_PASS_CONFORMA }}
        registry: quay.io/conforma

    - name: Tag latest release policy
      run: |
        set -euo pipefail

        for repo in enterprise-contract/ec-release-policy conforma/release-policy; do
          echo "Updating quay.io/${repo}:konflux"
          skopeo copy --all --digestfile image.digest \
            docker://quay.io/${repo}:latest docker://quay.io/${repo}:konflux

          echo -n "Image Digest: "
          cat image.digest
        done

    - name: Tag latest task policy
      run: |
        set -euo pipefail

        for repo in enterprise-contract/ec-task-policy conforma/task-policy; do
          echo "Updating quay.io/${repo}:konflux"
          skopeo copy --all --digestfile image.digest \
            docker://quay.io/${repo}:latest docker://quay.io/${repo}:konflux

          echo -n "Image Digest: "
          cat image.digest
        done
