---
name: konflux-policy

on:
  workflow_dispatch:
  schedule:
    # At 08:30 UTC on Tuesday
    - cron: '30 8 * * 2'

permissions:
  contents: read

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:

    - name: Log in to quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.BUNDLE_PUSH_USER_EC }}
        password: ${{ secrets.BUNDLE_PUSH_PASS_EC }}
        registry: quay.io

    - name: Tag latest release policy
      run: |
        set -euo pipefail

        skopeo copy --all --digestfile image.digest \
          docker://quay.io/enterprise-contract/ec-release-policy:latest \
          docker://quay.io/enterprise-contract/ec-release-policy:konflux

        echo -n "Image Digest: "
        cat image.digest

    - name: Tag latest task policy
      run: |
        set -euo pipefail

        skopeo copy --all --digestfile image.digest \
          docker://quay.io/enterprise-contract/ec-task-policy:latest \
          docker://quay.io/enterprise-contract/ec-task-policy:konflux

        echo -n "Image Digest: "
        cat image.digest
